# Generated by Django 5.2.8 on 2025-11-14 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_enregistrement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
